Title:
  Background:
    Text: '物品详情菜单'
  Prompt:
    Text: '%prompt%'
  BuyButton:
    Text: '%buy_button%'

CustomPapi:
  BackMenu:
    Enable: '取消'
    UnEnable: '关闭'
  PrePage:
    Enable: '可以上一页'
    UnEnable: '不可以上一页'
  NextPage:
    Enable: '可以下一页'
    UnEnable: '不可以下一页'
  BuyButton:
    Enable: '可以购买'
    UnEnable: '不可购买'
  Sort:
    Newest: '最新'
    Oldest: '即将过期'
    Expensive: '最昂贵'
    Cheapest: '最廉价'
  Prompt:
    Default: '市场找到了相同的物品'
    InsufficientAmount: '点击的物品因余额不足无法购买'

# # 默认材质
# A 返回 / 关闭
# B 刷新
# C 是预览物品
# D 点击购买
# E 同分类物品
# F 上一页
# G 下一页
# H 排序
# I 我的市场
Layout:
  - 'AB##C###D'
  - 'EEEEEEEEE'
  - 'EEEEEEEEE'
  - 'EEEEEEEEE'
  - 'EEEEEEEEE'
  - 'F#####GHI'

Icons:
  A:
    OpenDisplay:
      Mats: PAPER
      ModelData: 10000
      Name: '&E&L返回'
      Lore:
        - '&6&L返回'
    CloseDisplay:
      Mats: PAPER
      ModelData: 10000
      Name: '&E&L关闭'
      Lore:
        - '&6&L关闭'
  B:
    Display:
      Mats: PAPER
      ModelData: 10000
      Name: '&E&L刷新'
      Lore:
        - '&6&L刷新'
  D:
    ActiveDisplay:
      Mats: PAPER
      ModelData: 10000
      Name: '&E&L点击购买'
      Lore:
        - '&6&L点击购买'
    DisabledDisplay:
      Mats: PAPER
      ModelData: 10000
      Name: '&E&L金币不足'
      Lore:
        - '&6&L金币不足'
  F:
    ActiveDisplay:
      Mats: PAPER
      ModelData: 10000
      Name: '&E&L上一页'
      Lore:
        - '&6&L上一页'
    DisabledDisplay:
      Mats: PAPER
      ModelData: 10000
      Name: '&E&L上一页'
      Lore:
        - '&6&L上一页'
  G:
    ActiveDisplay:
      Mats: PAPER
      ModelData: 10000
      Name: '&E&L下一页'
      Lore:
        - '&6&L下一页'
    DisabledDisplay:
      Mats: PAPER
      ModelData: 10000
      Name: '&E&L下一页'
      Lore:
        - '&6&L下一页'
  H:
    NewestDisplay:
      Mats: PAPER
      ModelData: 10000
      Name: '&E&L最新上架'
      Lore:
        - '&6&L最新上架'
        - '&6&L即将到期'
        - '&6&L价格降序'
        - '&6&L价格升序'
    OldestDisplay:
      Mats: GLASS_PANE
      ModelData: 0
      Name: '&E&L即将过期'
      Lore:
        - '&6&L最新上架'
        - '&6&L即将到期'
        - '&6&L价格降序'
        - '&6&L价格升序'
    ExpensiveDisplay:
      Mats: GLASS_PANE
      ModelData: 0
      Name: '&6&L价格降序'
      Lore:
        - '&6&L最新上架'
        - '&6&L即将到期'
        - '&6&L价格降序'
        - '&6&L价格升序'
    CheapestDisplay:
      Mats: GLASS_PANE
      ModelData: 0
      Name: '&6&L价格升序'
      Lore:
        - '&6&L最新上架'
        - '&6&L即将到期'
        - '&6&L价格降序'
        - '&6&L价格升序'
  I:
    Display:
      Mats: PAPER
      ModelData: 10000
      Name: '&E&L我的市场'
      Lore:
        - '&6&L我的市场'